<?php

namespace ContainerFrQe1K0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A7Rv4xfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A7Rv4xf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A7Rv4xf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Controller::about' => ['privates', '.service_locator.v5rNe.V', 'get_ServiceLocator_V5rNe_VService', true],
            'App\\Controller\\Controller::home' => ['privates', '.service_locator.v5rNe.V', 'get_ServiceLocator_V5rNe_VService', true],
            'App\\Controller\\Controller::index' => ['privates', '.service_locator.v5rNe.V', 'get_ServiceLocator_V5rNe_VService', true],
            'App\\Controller\\Controller::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\ProduitController::ProduitShow' => ['privates', '.service_locator.3zcMOVM', 'get_ServiceLocator_3zcMOVMService', true],
            'App\\Controller\\ProduitController::article' => ['privates', '.service_locator.VP68NKc', 'get_ServiceLocator_VP68NKcService', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.3zcMOVM', 'get_ServiceLocator_3zcMOVMService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.3zcMOVM', 'get_ServiceLocator_3zcMOVMService', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.VP68NKc', 'get_ServiceLocator_VP68NKcService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.3zcMOVM', 'get_ServiceLocator_3zcMOVMService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\Controller:about' => ['privates', '.service_locator.v5rNe.V', 'get_ServiceLocator_V5rNe_VService', true],
            'App\\Controller\\Controller:home' => ['privates', '.service_locator.v5rNe.V', 'get_ServiceLocator_V5rNe_VService', true],
            'App\\Controller\\Controller:index' => ['privates', '.service_locator.v5rNe.V', 'get_ServiceLocator_V5rNe_VService', true],
            'App\\Controller\\Controller:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\ProduitController:ProduitShow' => ['privates', '.service_locator.3zcMOVM', 'get_ServiceLocator_3zcMOVMService', true],
            'App\\Controller\\ProduitController:article' => ['privates', '.service_locator.VP68NKc', 'get_ServiceLocator_VP68NKcService', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.3zcMOVM', 'get_ServiceLocator_3zcMOVMService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.3zcMOVM', 'get_ServiceLocator_3zcMOVMService', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.VP68NKc', 'get_ServiceLocator_VP68NKcService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.3zcMOVM', 'get_ServiceLocator_3zcMOVMService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\Controller::about' => '?',
            'App\\Controller\\Controller::home' => '?',
            'App\\Controller\\Controller::index' => '?',
            'App\\Controller\\Controller::login' => '?',
            'App\\Controller\\ProduitController::ProduitShow' => '?',
            'App\\Controller\\ProduitController::article' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Controller:about' => '?',
            'App\\Controller\\Controller:home' => '?',
            'App\\Controller\\Controller:index' => '?',
            'App\\Controller\\Controller:login' => '?',
            'App\\Controller\\ProduitController:ProduitShow' => '?',
            'App\\Controller\\ProduitController:article' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
