<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFrQe1K0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFrQe1K0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFrQe1K0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFrQe1K0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFrQe1K0\App_KernelDevDebugContainer([
    'container.build_hash' => 'FrQe1K0',
    'container.build_id' => '128abf4e',
    'container.build_time' => 1605792044,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFrQe1K0');
